// Food database for GERD-friendly meals
// Organized by time of day and meal type
// All foods are common Indonesian dishes, affordable, easy to find, and GERD-friendly

const foodDatabase = {
  "Sarapan/Pagi": {
    nasi: [
      "Nasi putih + telur rebus",
      "Nasi putih + tumis kangkung",
      "Nasi putih + tempe orek",
      "Nasi putih + tahu bacem",
      "Nasi putih + sambal terasi sedikit",
      "Nasi putih + oseng labu siam",
      "Nasi putih + sayur bening",
      "Nasi putih + perkedel kentang",
      "Nasi putih + ayam suwir",
      "Nasi putih + telur ceplok",
      "Nasi putih + tumis taoge",
      "Nasi putih + oseng pare",
      "Nasi putih + sayur lodeh encer",
      "Nasi putih + pepes ikan",
      "Nasi putih + tumis genjer",
      "Nasi putih + sayur asam",
      "Nasi putih + dadar telur",
      "Nasi putih + oseng kacang panjang",
      "Nasi putih + tumis wortel",
      "Nasi putih + sambal bajak sedikit",
      "Nasi uduk (tanpa bawang goreng dan kacang)",
      "Nasi kuning (bumbu ringan)",
      "Nasi goreng putih (tanpa cabai)",
      "Nasi tim ayam jamur",
      "Nasi bakar (isi tidak pedas)",
      "Lontong sayur (kuah encer)",
      "Nasi dengan sup tahu",
      "Nasi dengan tumis buncis",
      "Nasi dengan orak-arik telur",
      "Nasi dengan ayam pop",
      "Nasi liwet (versi gurih, tidak pedas)",
      "Nasi dengan semur tahu kentang",
      "Nasi dengan bacem tempe dan tahu",
      "Nasi dengan sayur bobor bayam",
      "Nasi dengan tumis jamur tiram",
      "Nasi dengan telur pindang",
      "Nasi dengan cah sawi hijau",
      "Nasi dengan empal suwir (tidak pedas)",
      "Nasi dengan rolade ayam",
      "Nasi dengan sate ayam (bumbu kacang encer)",
      "Nasi dengan garang asem (tanpa cabai)",
      "Nasi dengan pindang bandeng",
      "Nasi dengan ayam ungkep goreng",
      "Nasi dengan tumis labu kuning",
      "Nasi dengan capcay kuah (sedikit sayur kol)",
      "Nasi dengan bakmoy ayam",
      "Nasi dengan sup kimlo",
      "Nasi dengan ayam kodok (potongan kecil)",
      "Nasi dengan terik daging (santan encer)",
      "Nasi dengan brenebon (sup kacang merah, tanpa cabai)",
    ],
    nonNasi: [
      "Bubur ayam (tanpa kulit)",
      "Bubur sumsum",
      "Roti gandum + selai kacang",
      "Kentang rebus + telur rebus",
      "Sandwich roti gandum isi telur",
      "Sereal rendah gula + susu",
      "Telur rebus + roti gandum",
      "Sup krim jagung (encer)",
      "Sup bening sayur",
      "Salad buah sederhana",
      "Toast alpukat + telur rebus",
      "Mashed potato + ayam suwir",
      "Quinoa salad dengan sayur",
      "Yogurt + granola rendah gula",
      "Telur dadar rendah minyak",
      "Roti gandum + keju rendah lemak",
      "Bihun kuah dengan ayam suwir",
      "Kwetiau rebus dengan sayuran",
      "Roti bakar dengan madu",
      "Pancake dengan sirup maple (sedikit)",
      "Ubi rebus",
      "Singkong rebus",
      "Talas rebus",
      "Jagung rebus",
      "Bubur kacang hijau (santan encer, sedikit gula)",
      "Bubur ketan hitam (santan encer, sedikit gula)",
      "Muesli dengan susu rendah lemak",
      "Scrambled egg (sedikit minyak)",
      "Poached egg dengan roti gandum",
      "Sup oyong (gambas) dengan soun",
      "Pastel tutup (tanpa isian pedas)",
      "Lontong isi sayur",
      "Arem-arem isi ayam",
      "Serabi (tanpa kuah kinca manis)",
      "Getuk lindri",
      "Cenil (sedikit kelapa parut)",
      "Klepon (isi gula merah sedikit)",
      "Lupis",
      "Tiwul",
      "Gatot",
      "Horok-horok",
      "Papeda (versi gurih)",
      "Sagu ambon",
      "Tinutuan (Bubur Manado, tanpa sambal)",
      "Ketan srikaya",
    ],
  },
  "Makan Siang": {
    nasi: [
      "Nasi putih + ayam bakar (tanpa kulit)",
      "Nasi putih + ikan tongkol balado",
      "Nasi putih + tahu bacem",
      "Nasi putih + tempe orek",
      "Nasi putih + tumis kangkung",
      "Nasi putih + sayur lodeh encer",
      "Nasi putih + pepes ikan",
      "Nasi putih + oseng labu siam",
      "Nasi putih + tumis taoge",
      "Nasi putih + gulai nangka muda",
      "Nasi putih + ayam suwir",
      "Nasi putih + telur balado",
      "Nasi putih + perkedel kentang",
      "Nasi putih + sambal terasi sedikit",
      "Nasi putih + sayur asam",
      "Nasi putih + ikan asin goreng (sedikit)",
      "Nasi putih + tumis genjer",
      "Nasi putih + oseng pare",
      "Nasi putih + sayur bening",
      "Nasi putih + oseng kacang panjang",
      "Nasi campur (pilih lauk tidak pedas)",
      "Nasi rawon (daging empuk, kuah bening)",
      "Nasi soto ayam bening",
      "Nasi gudeg (versi tidak terlalu manis)",
      "Nasi pindang kudus",
      "Nasi bogana (pilih lauk tidak pedas)",
      "Nasi begana",
      "Nasi grombyang",
      "Nasi krawu (tanpa sambal)",
      "Nasi megono",
      "Nasi gandul (kuah tidak kental)",
      "Nasi pecel (bumbu tidak pedas)",
      "Nasi urap (bumbu tidak pedas)",
      "Nasi rames (pilih lauk tidak pedas)",
      "Nasi dengan asem-asem daging",
      "Nasi dengan brongkos (santan encer)",
      "Nasi dengan mangut lele (tanpa cabai)",
      "Nasi dengan opor ayam",
      "Nasi dengan gulai ikan (tidak pedas)",
      "Nasi dengan sate lilit (bumbu ringan)",
      "Nasi dengan ayam betutu (bumbu ringan)",
      "Nasi dengan lawar (tanpa darah, tidak pedas)",
      "Nasi dengan bothok (tanpa cabai)",
      "Nasi dengan garang asem ayam",
      "Nasi dengan pindang iga",
      "Nasi dengan sop saudara (kuah bening)",
      "Nasi dengan coto makassar (kuah bening)",
      "Nasi dengan pallubasa (kuah bening)",
      "Nasi dengan konro (kuah bening)",
      "Nasi dengan barobbo",
    ],
    nonNasi: [
      "Mie rebus kuah bening + ayam suwir",
      "Mie goreng rendah minyak",
      "Sup bening sayur + telur rebus",
      "Sup krim ayam (encer)",
      "Kentang rebus + ayam panggang",
      "Quinoa salad dengan sayur",
      "Pasta rebus + saus tomat segar",
      "Sandwich roti gandum isi ayam",
      "Salad sayur + ayam rebus",
      "Telur rebus + roti gandum",
      "Bubur ayam (tanpa kulit)",
      "Omelet sayur rendah minyak",
      "Mashed potato + ikan panggang",
      "Soup bening + tahu",
      "Salad quinoa + sayur",
      "Roti gandum + keju rendah lemak + selada",
      "Yogurt + granola rendah gula",
      "Pasta rebus + tumis sayur",
      "Sup krim jagung (encer)",
      "Bakso kuah bening",
      "Soto mie (tanpa risol dan cabai)",
      "Laksa (kuah encer, tidak pedas)",
      "Toge goreng (tanpa tauco banyak)",
      "Asinan sayur (kuah tidak pedas/asam)",
      "Gado-gado (bumbu kacang encer)",
      "Ketoprak (bumbu kacang encer)",
      "Siomay (rebus, bumbu kacang encer)",
      "Batagor (kuah, bumbu kacang encer)",
      "Pempek (rebus, kuah cuka sedikit)",
      "Tekwan",
      "Model",
      "Laksan",
      "Celimpungan",
      "Burgo",
      "Sate padang (kuah tidak pedas)",
      "Sate klathak",
      "Sate kere",
      "Sate buntel",
      "Tongseng (tanpa kol dan cabai)",
      "Gecok",
      "Empal gentong (kuah bening)",
      "Doclang",
      "Kupat tahu (bumbu ringan)",
      "Lontong balap (tanpa petis)",
      "Rujak soto (bumbu ringan)",
      "Sega jamblang (pilih lauk tidak pedas)",
      "Emping melinjo (sedikit)",
      "Kerupuk kulit (sedikit)",
      "Rempeyek (sedikit)",
    ],
  },
  "Makan Malam": {
    nasi: [
      "Nasi putih + sayur bening",
      "Nasi putih + tumis kangkung",
      "Nasi putih + sup ayam bening",
      "Nasi putih + oseng labu siam",
      "Nasi putih + tumis taoge",
      "Nasi putih + sayur lodeh encer",
      "Nasi putih + gulai nangka muda",
      "Nasi putih + pepes ikan",
      "Nasi putih + tumis genjer",
      "Nasi putih + oseng pare",
      "Nasi putih + sayur asam",
      "Nasi putih + sambal terasi sedikit",
      "Nasi putih + perkedel kentang",
      "Nasi putih + telur balado",
      "Nasi putih + ayam suwir",
      "Nasi putih + tahu bacem",
      "Nasi putih + tempe orek",
      "Nasi putih + oseng kacang panjang",
      "Nasi putih + tumis wortel",
      "Nasi putih + sayur sop",
      "Nasi dengan sup bola-bola tahu",
      "Nasi dengan tumis brokoli",
      "Nasi dengan cah kailan bawang putih",
      "Nasi dengan sapo tahu",
      "Nasi dengan fuyunghai (saus tidak asam)",
      "Nasi dengan capcay goreng",
      "Nasi dengan ifumie (kuah tidak kental)",
      "Nasi dengan kwetiau siram",
      "Nasi dengan bihun goreng",
      "Nasi dengan mi goreng",
      "Nasi dengan ayam kuluyuk (saus tidak asam)",
      "Nasi dengan bistik ayam",
      "Nasi dengan rolade sapi",
      "Nasi dengan galantin",
      "Nasi dengan semur lidah",
      "Nasi dengan sup matahari",
      "Nasi dengan timlo solo",
      "Nasi dengan sup manten",
      "Nasi dengan selat solo",
      "Nasi dengan gadon daging",
      "Nasi dengan schotel (makaroni panggang)",
      "Nasi dengan pastel tutup",
      "Nasi dengan zupa-zupa sup",
      "Nasi dengan sup asparagus",
      "Nasi dengan sup kepiting",
      "Nasi dengan cah jagung muda",
      "Nasi dengan tumis putren",
      "Nasi dengan oseng cumi (tidak pedas)",
      "Nasi dengan udang goreng tepung",
      "Nasi dengan ikan bakar madu",
    ],
    nonNasi: [
      "Bubur sumsum",
      "Sup bening sayur",
      "Sup krim jagung (encer)",
      "Mashed potato + ikan panggang",
      "Quinoa salad dengan sayur",
      "Yogurt + granola rendah gula",
      "Soup bening + tahu",
      "Salad sayur + ayam rebus",
      "Pasta rebus + saus tomat segar",
      "Sandwich roti gandum isi telur",
      "Telur rebus + roti gandum",
      "Sup krim ayam (encer)",
      "Salad quinoa + sayur",
      "Mie rebus kuah bening + ayam suwir",
      "Roti gandum + keju rendah lemak + selada",
      "Sereal rendah gula + susu",
      "Pasta rebus + tumis sayur",
      "Kentang rebus + ayam panggang",
      "Makaroni schotel",
      "Lasagna (saus tomat tidak asam)",
      "Spaghetti bolognese (daging cincang, saus ringan)",
      "Fettuccine carbonara (saus tidak kental)",
      "Pizza (topping tidak asam/pedas)",
      "Crepes (isi tidak manis/asam)",
      "Martabak telur (tidak banyak minyak)",
      "Martabak manis (topping keju/susu)",
      "Pukis",
      "Kue cubit (setengah matang)",
      "Serabi solo",
      "Leker",
      "Terang bulan",
      "Roti john",
      "Gulai roti canai",
      "Pho (sup vietnam)",
      "Ramen (kuah shoyu/miso ringan)",
      "Udon (kuah bening)",
      "Tom yum (kuah bening, tidak pedas/asam)",
      "Capcay kuah",
      "Sapo tahu seafood",
      "Ifumie siram sayur",
      "Kwetiau kuah",
      "Bihun kuah",
      "Mi kuah",
      "Bakmi godog jawa",
      "Seblak (kerupuk rebus, bumbu tidak pedas)",
      "Cilok kuah",
      "Cireng kuah",
      "Batagor kuah",
    ],
  },
};

module.exports = { foodDatabase };
