// Food database for GERD-friendly meals
// Organized by time of day and meal type
// All foods are common Indonesian dishes, affordable, easy to find, and GERD-friendly

const foodDatabase = {
  "Sarapan/Pagi": {
    nasi: [
      "Nasi putih + telur rebus",
      "Nasi putih + tumis kangkung",
      "Nasi putih + tempe orek",
      "Nasi putih + tahu bacem",
      "Nasi putih + sambal terasi sedikit",
      "Nasi putih + oseng labu siam",
      "Nasi putih + sayur bening",
      "Nasi putih + perkedel kentang",
      "Nasi putih + ayam suwir",
      "Nasi putih + telur ceplok",
      "Nasi putih + tumis taoge",
      "Nasi putih + oseng pare",
      "Nasi putih + sayur lodeh encer",
      "Nasi putih + pepes ikan",
      "Nasi putih + tumis genjer",
      "Nasi putih + sayur asam",
      "Nasi putih + dadar telur",
      "Nasi putih + oseng kacang panjang",
      "Nasi putih + tumis wortel",
      "Nasi putih + sambal bajak sedikit"
    ],
    nonNasi: [
      "Bubur ayam (tanpa kulit)",
      "Bubur sumsum",
      "Oatmeal dengan pisang",
      "Roti gandum + selai kacang",
      "Kentang rebus + telur rebus",
      "Sandwich roti gandum isi telur",
      "Sereal rendah gula + susu",
      "Smoothie pisang + susu",
      "Telur rebus + roti gandum",
      "Sup krim jagung (encer)",
      "Sup bening sayur",
      "Pisang + yoghurt rendah lemak",
      "Salad buah sederhana",
      "Toast alpukat + telur rebus",
      "Mashed potato + ayam suwir",
      "Quinoa salad dengan sayur",
      "Yogurt + granola rendah gula",
      "Telur dadar rendah minyak",
      "Roti gandum + keju rendah lemak"
    ]
  },
  "Makan Siang": {
    nasi: [
      "Nasi putih + ayam bakar (tanpa kulit)",
      "Nasi putih + ikan tongkol balado",
      "Nasi putih + tahu bacem",
      "Nasi putih + tempe orek",
      "Nasi putih + tumis kangkung",
      "Nasi putih + sayur lodeh encer",
      "Nasi putih + pepes ikan",
      "Nasi putih + oseng labu siam",
      "Nasi putih + tumis taoge",
      "Nasi putih + gulai nangka muda",
      "Nasi putih + ayam suwir",
      "Nasi putih + telur balado",
      "Nasi putih + perkedel kentang",
      "Nasi putih + sambal terasi sedikit",
      "Nasi putih + sayur asam",
      "Nasi putih + ikan asin goreng (sedikit)",
      "Nasi putih + tumis genjer",
      "Nasi putih + oseng pare",
      "Nasi putih + sayur bening",
      "Nasi putih + oseng kacang panjang"
    ],
    nonNasi: [
      "Mie rebus kuah bening + ayam suwir",
      "Mie goreng rendah minyak",
      "Sup bening sayur + telur rebus",
      "Sup krim ayam (encer)",
      "Kentang rebus + ayam panggang",
      "Quinoa salad dengan sayur",
      "Pasta rebus + saus tomat segar",
      "Sandwich roti gandum isi ayam",
      "Salad sayur + ayam rebus",
      "Telur rebus + roti gandum",
      "Smoothie sayur + pisang",
      "Bubur ayam (tanpa kulit)",
      "Omelet sayur rendah minyak",
      "Mashed potato + ikan panggang",
      "Soup bening + tahu",
      "Salad quinoa + sayur",
      "Roti gandum + keju rendah lemak + selada",
      "Yogurt + granola rendah gula",
      "Pasta rebus + tumis sayur",
      "Sup krim jagung (encer)"
    ]
  },
  "Makan Malam": {
    nasi: [
      "Nasi putih + sayur bening",
      "Nasi putih + tumis kangkung",
      "Nasi putih + sup ayam bening",
      "Nasi putih + oseng labu siam",
      "Nasi putih + tumis taoge",
      "Nasi putih + sayur lodeh encer",
      "Nasi putih + gulai nangka muda",
      "Nasi putih + pepes ikan",
      "Nasi putih + tumis genjer",
      "Nasi putih + oseng pare",
      "Nasi putih + sayur asam",
      "Nasi putih + sambal terasi sedikit",
      "Nasi putih + perkedel kentang",
      "Nasi putih + telur balado",
      "Nasi putih + ayam suwir",
      "Nasi putih + tahu bacem",
      "Nasi putih + tempe orek",
      "Nasi putih + oseng kacang panjang",
      "Nasi putih + tumis wortel",
      "Nasi putih + sayur sop"
    ],
    nonNasi: [
      "Bubur sumsum",
      "Sup bening sayur",
      "Sup krim jagung (encer)",
      "Mashed potato + ikan panggang",
      "Quinoa salad dengan sayur",
      "Yogurt + granola rendah gula",
      "Smoothie sayur + pisang",
      "Oatmeal dengan pisang",
      "Soup bening + tahu",
      "Salad sayur + ayam rebus",
      "Pasta rebus + saus tomat segar",
      "Sandwich roti gandum isi telur",
      "Telur rebus + roti gandum",
      "Sup krim ayam (encer)",
      "Salad quinoa + sayur",
      "Mie rebus kuah bening + ayam suwir",
      "Roti gandum + keju rendah lemak + selada",
      "Sereal rendah gula + susu",
      "Pasta rebus + tumis sayur",
      "Kentang rebus + ayam panggang"
    ]
  }
};

module.exports = { foodDatabase };